"""
MetaLeadIQ Database Seeder
Seeds the SQLite database with the prioritized leads generated by the pipeline.
"""
import logging
import re
import os
import json
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from backend.database import init_db, bulk_insert_leads, get_lead_count

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def seed_database(force: bool = False):
    """Seed SQLite database with initial leads if empty or forced."""
    init_db()
    current_count = get_lead_count()
    if current_count > 0 and not force:
        logger.info(f"Database already contains {current_count} leads. Skipping seed.")
        return current_count

    # Prefer reading from src/data/mockData.ts (has realistic names, phone, email)
    mock_data_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'mockData.ts')
    leads_to_insert = []

    if os.path.exists(mock_data_path):
        with open(mock_data_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Extract JSON array from TypeScript file
        match = re.search(r'export const mockLeads:\s*Lead\[\]\s*=\s*(\[.*?\]);', content, re.DOTALL)
        if match:
            raw_leads = json.loads(match.group(1))
            for l in raw_leads:
                lead_dict = {
                    'id': l['id'],
                    'name': l['name'],
                    'email': l['email'],
                    'phone': l['phone'],
                    'lead_source': l.get('leadSource', 'Unknown'),
                    'lead_origin': l.get('leadOrigin', 'Unknown'),
                    'placement': l.get('placement', 'Feed'),
                    'audience_type': l.get('audienceType', 'Broad'),
                    'ctr': float(l.get('ctr', 0.0)),
                    'cpc': float(l.get('cpc', 0.0)),
                    'creative_type': l.get('creativeType', 'Video'),
                    'total_visits': int(l.get('totalVisits', 1)),
                    'time_on_website': float(l.get('timeOnWebsite', 0.0)),
                    'page_views': int(l.get('pageViews', 1)),
                    'last_activity': l.get('lastActivity', 'Unknown'),
                    'base_score': int(l.get('baseScore', 50)),
                    'base_probability': float(l.get('conversionProbability', 50)) / 100.0,
                    'calibrated_probability': float(l.get('conversionProbability', 50)) / 100.0,
                    'decayed_score': int(l.get('currentScore', 50)),
                    'hours_uncontacted': float(l.get('hoursUncontacted', 0.0)),
                    'status': l.get('status', 'Warm'),
                    'confidence': l.get('confidence', 'Uncertain'),
                    'prediction_lower': int(l.get('predictionLower', 40)),
                    'prediction_upper': int(l.get('predictionUpper', 60)),
                    'submission_time': l.get('submissionTime', ''),
                    'contacted': 1 if l.get('contacted') else 0,
                    'contacted_at': None,
                }
                leads_to_insert.append(lead_dict)

    if not leads_to_insert:
        # Fallback to priority_queue.json
        pq_path = os.path.join(os.path.dirname(__file__), 'data', 'priority_queue.json')
        if os.path.exists(pq_path):
            with open(pq_path, 'r', encoding='utf-8') as f:
                pq_leads = json.load(f)[:200]
                for idx, l in enumerate(pq_leads):
                    leads_to_insert.append({
                        'id': f"L-{1000 + idx}",
                        'name': f"Lead {1000 + idx}",
                        'email': f"lead{1000 + idx}@example.com",
                        'phone': f"+1 (555) 000-{1000 + idx}",
                        'lead_source': l.get('Lead Source', 'Unknown'),
                        'lead_origin': l.get('Lead Origin', 'Unknown'),
                        'placement': l.get('meta_ad_placement', 'Feed'),
                        'audience_type': l.get('meta_audience_type', 'Broad'),
                        'ctr': float(l.get('meta_ctr', 0.0)),
                        'cpc': float(l.get('meta_cpc', 0.0)),
                        'creative_type': 'Video',
                        'total_visits': int(l.get('TotalVisits', 1)),
                        'time_on_website': float(l.get('Total Time Spent on Website', 0.0)) / 60.0,
                        'page_views': int(l.get('Page Views Per Visit', 1)),
                        'last_activity': l.get('Last Activity', 'Unknown'),
                        'base_score': int(l.get('base_score', 50)),
                        'base_probability': float(l.get('base_probability', 0.5)),
                        'calibrated_probability': float(l.get('calibrated_probability', 0.5)),
                        'decayed_score': int(l.get('decayed_score', 50)),
                        'hours_uncontacted': float(l.get('hours_uncontacted', 0.0)),
                        'status': l.get('lead_status', 'Warm'),
                        'confidence': l.get('confidence', 'Uncertain'),
                        'prediction_lower': int(l.get('prediction_lower', 40)),
                        'prediction_upper': int(l.get('prediction_upper', 60)),
                        'submission_time': l.get('created_at', ''),
                        'contacted': 0,
                        'contacted_at': None,
                    })

    if leads_to_insert:
        bulk_insert_leads(leads_to_insert)
        logger.info(f"Database seeded successfully with {len(leads_to_insert)} records.")
    return len(leads_to_insert)


if __name__ == '__main__':
    seed_database(force=True)
